version: '2'

services:
  nginx:
    build:
      context: dockerfiles/nginx
    volumes:
      - ./assets:/app/public
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
