apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-webroot
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webroot
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi